#!/usr/bin/env python3
"""Turns ca/cacert.pem into a C file: g_cacert_pem (NUL-terminated, as Mbed TLS wants for PEM) and its size."""
import sys

src, dst = sys.argv[1], sys.argv[2]
data = open(src, 'rb').read()
# Only the certificates (comments are fine for Mbed TLS, but keep the data plain).
out = ['/* Generated by tools/embed.py from ca/cacert.pem. */', '#include <stddef.h>',
       'const char g_cacert_pem[] = {']
row = []
for i, b in enumerate(data + b'\0'):
    row.append('%d' % b)
    if len(row) == 24:
        out.append('  ' + ','.join(row) + ',')
        row = []
if row:
    out.append('  ' + ','.join(row) + ',')
out.append('};')
out.append('const size_t g_cacert_pem_size = sizeof(g_cacert_pem);')
open(dst, 'w').write('\n'.join(out) + '\n')
