#!/usr/bin/env python3
"""history/<build>.json -> C tables of what earlier test builds shipped in PCSX2/ (file SHA-256s and switch names).

The installer uses them the first time it runs on a console set up by hand: a file that is byte for byte an
earlier build's copy was not changed by the user, so a new build may replace it; a switch that no earlier
build shipped is new, so it may be added."""
import glob
import json
import sys

out = sys.argv[1]
files = {}
flags = set()
for path in sorted(glob.glob(sys.argv[2] + '/*.json')):
    h = json.load(open(path))
    for key, versions in h.get('files', {}).items():
        files.setdefault(key, set()).update(versions)
    flags.update(h.get('flags', {}))


def c_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


lines = ['/* Generated by tools/history.py from history/<build>.json. */', '#include "history.h"', '',
         'const shipped_file g_shipped_files[] = {']
for key in sorted(files):
    for sha in sorted(files[key]):
        assert len(sha) == 64 and all(c in '0123456789abcdef' for c in sha)
        lines.append('  {%s, "%s"},' % (c_str(key), sha))
lines.append('};')
lines.append('const size_t g_shipped_files_n = sizeof(g_shipped_files) / sizeof(g_shipped_files[0]);')
lines.append('const char *const g_shipped_flags[] = {')
for f in sorted(flags):
    lines.append('  %s,' % c_str(f))
lines.append('};')
lines.append('const size_t g_shipped_flags_n = sizeof(g_shipped_flags) / sizeof(g_shipped_flags[0]);')
open(out, 'w').write('\n'.join(lines) + '\n')
